FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y\
    git\
    automake\
    g++\
    gcc\
    libssl-dev\
    libtool\
    pkg-config\
    libmysqlclient-dev

#    gdb\
#    gdbserver\
#    libmysqlclient-dev\

RUN cd /opt; git clone https://github.com/akopytov/sysbench.git
RUN cd /opt/sysbench; ./autogen.sh; ./configure --bindir=/usr/bin; make; make install
RUN ls /opt/sysbench
CMD ["tail", "-f", "/opt/sysbench/README.md"] 
